---
title: "habitat_quality_model"
author: "Hanna Weyland"
date: "1/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(here)
library(tidyverse)
library(janitor)
library(stars)
library(rgdal)
```

## Scenario 1 2020 

```{r}
# read in raster for 2020
scenario_raster_scenario1_2020 <- read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210824_1050_0.tif"))

#vectorize 2020 raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2020 <- st_as_sf(scenario_raster_scenario1_2020[1], merge = FALSE, as_points = F)
```

```{r}
#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2020) <- 3310

#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2020) <- c("gridcode", "geometry")

#put scenario vector into lulc_select to be able to break apart lulc code 
lulc_select <- scenario_vector_scenario1_2020

#let's break apart landuse stuff 
lulc_sep_2020 <- lulc_select %>% 
  mutate(last_2 = lulc_select$gridcode %% 100) %>%
  mutate(first_two = substr(lulc_select$gridcode, 1, nchar(lulc_select$gridcode)-2 )) 

#separate the number in the gridcode to create new columns
lulc_sep_2020 <- lulc_sep_2020 %>% 
  mutate(second_last = substr(lulc_sep_2020$last_2, 1, 1) ) %>% 
  mutate(first_last = lulc_select$gridcode %% 10) %>% 
  mutate(forest_type = first_two) %>% 
  mutate(seral_stage = second_last) %>% 
  mutate(canopy_cover = first_last) %>% 
  mutate(ecoregion_type = as.numeric(forest_type)) #ecoregion type will be the reclassified column of forest types

#write it out into shape file!
st_write(lulc_sep_2060, "tcsi_landcover_2020.shp")
```

```{r}
#make no values into 0; will need to change for GP analysis
#lulc_sep_2020$first_two[lulc_sep_2020$first_two == ""] <- 0
#lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == ""] <- 0
```


```{r}
#reclassify land use to create new land cover code
#rename based on the document by TNC: Forest Type
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 0] <- "non-forested"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 1] <- "aspen"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 2] <- "montane_hardwood"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 3] <- "montane_riparian"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 4] <- "white_fir"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 5] <- "red_fir"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 6] <- "jeffrey_pine"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 7] <- "ponderosa_pine"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 8] <- "douglas-fir"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 9] <- "mixed_hardwood_conifer"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 10] <- "lodgepole_pine"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 11] <- "sierra_mixed_conifer"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 12] <- "sierra_high_elevation_mixed_conifer"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 13] <- "juniper"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 14] <- "chapparal"
#rename based on the document by TNC: Seral Stage
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 0] <- "NA"
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 1] <- "below_1"
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 2] <- "1-6"
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 3] <- "6-11"
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 4] <- "11-24"
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 5] <- "above_24"
#rename based on the document by TNC: canopy cover
lulc_sep_2020$canopy_cover[lulc_sep_2020$canopy_cover == 0] <- "0-10"
lulc_sep_2020$canopy_cover[lulc_sep_2020$canopy_cover == 1] <- "10-25"
lulc_sep_2020$canopy_cover[lulc_sep_2020$canopy_cover == 2] <- "25-40"
lulc_sep_2020$canopy_cover[lulc_sep_2020$canopy_cover == 3] <- "40-60"
lulc_sep_2020$canopy_cover[lulc_sep_2020$canopy_cover == 4] <- "60-100"
```

#Scenario 1 2060

```{r}
#data wrangling for 2060

# read in raster for 2060
scenario_raster_scenario1_2060 <-  read_stars(here("data", "cwhr_MIROC5_85_Scenario1_v3_20210824_1050_40.tif"))

#vectorize 2060 raster to be able to perform the habitat quality table fix
scenario_vector_scenario1_2060 <- st_as_sf(scenario_raster_scenario1_2060[1], merge = FALSE, as_points = F)

#set crs to NAD83 UTM zone 10
st_crs(scenario_vector_scenario1_2060) <- 3310

#set column names to grid code and geometry
colnames(scenario_vector_scenario1_2060) <- c("gridcode", "geometry")

#put scenario vector into lulc_select to be able to break apart lulc code 
lulc_select <- scenario_vector_scenario1_2060

#let's break apart landuse stuff 
lulc_sep_2060 <- lulc_select %>% 
  mutate(last_2 = lulc_select$gridcode %% 100) %>%
  mutate(first_two = substr(lulc_select$gridcode, 1, nchar(lulc_select$gridcode)-2 )) 

#separate the number in the gridcode to create new columns
lulc_sep_2060 <- lulc_sep_2060 %>% 
  mutate(second_last = substr(lulc_sep_2060$last_2, 1, 1) ) %>% 
  mutate(first_last = lulc_select$gridcode %% 10) %>% 
  mutate(forest_type = first_two) %>% 
  mutate(seral_stage = second_last) %>% 
  mutate(canopy_cover = first_last) %>% 
  mutate(ecoregion_type = as.numeric(forest_type)) #ecoregion type will be the reclassified column of forest types

#write it out into shape file!
st_write(lulc_sep_2060, "tcsi_landcover_2060.shp")
```



```{r}
#make no values into 0; will need to change for GP analysis - TAKE OUT 
#lulc_sep_2060$first_two[lulc_sep_2060$first_two == ""] <- 0
#lulc_sep_2060$forest_type[lulc_sep_2060$forest_type == ""] <- 0
```

```{r}

#reclassify land use to create new land cover code
#rename based on the document by TNC: Forest Type
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 0] <- "non-forested"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 1] <- "aspen"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 2] <- "montane_hardwood"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 3] <- "montane_riparian"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 4] <- "white_fir"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 5] <- "red_fir"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 6] <- "jeffrey_pine"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 7] <- "ponderosa_pine"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 8] <- "douglas-fir"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 9] <- "mixed_hardwood_conifer"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 10] <- "lodgepole_pine"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 11] <- "sierra_mixed_conifer"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 12] <- "sierra_high_elevation_mixed_conifer"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 13] <- "juniper"
lulc_sep_2020$forest_type[lulc_sep_2020$forest_type == 14] <- "chapparal"

#rename based on the document by TNC: Seral Stage
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 0] <- "NA"
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 1] <- "below_1"
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 2] <- "1-6"
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 3] <- "6-11"
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 4] <- "11-24"
lulc_sep_2020$seral_stage[lulc_sep_2020$seral_stage == 5] <- "above_24"
#rename based on the document by TNC: canopy cover
lulc_sep_2020$canopy_cover[lulc_sep_2020$canopy_cover == 0] <- "0-10"
lulc_sep_2020$canopy_cover[lulc_sep_2020$canopy_cover == 1] <- "10-25"
lulc_sep_2020$canopy_cover[lulc_sep_2020$canopy_cover == 2] <- "25-40"
lulc_sep_2020$canopy_cover[lulc_sep_2020$canopy_cover == 3] <- "40-60"
lulc_sep_2020$canopy_cover[lulc_sep_2020$canopy_cover == 4] <- "60-100"
```



```{r}

#mutate <- column for numbers "forest_type_num"
#create new data frame with the column, assuming they have the same number of cells or organize based on geometry
mutate <- df to make a df2$column - df1$column,


name <- c(df1$column, df2$column) %>% 
  mutate(new column = df1$column - df2$column) 


df1 and 2 geometries 

#take the difference between the two
difference<- scenario_vector_scenario1_2040$gridcode - scenario_vector_scenario1_2020$gridcode
#create data frame
difference_dataframe <- as.data.frame(difference)


scenario_2020 <- 2020 %>% mutate(column = "column")

compare_df_cols(df, df_missing, df_extra, df_class, df_order)

#mutate if column a in dataframe a is different than column b in dataframe b otherwise keep... 

if df1$column == df2$column then new column name == df2$column if else == something 


```














```{r}
#change 0-10% canopy cover to non-forested ecoregion; 0-10% canopy cover does not count as forest
lulc_sep_2020$ecoregion_type <- with(lulc_sep_2020, ifelse(lulc_sep_2020$canopy_cover == "0-10", lulc_sep_2020$ecoregion_type * 0, lulc_sep_2020$ecoregion_type*1))

#reclassify ecoregion_type as non-forest, hardwoods, conifer, or mixed     
lulc_sep_2020$ecoregion_type[lulc_sep_2020$ecoregion_type == 0 ] <- "non-forest" 
lulc_sep_2020$ecoregion_type[lulc_sep_2020$ecoregion_type== 14] <- "shrub"
lulc_sep_2020$ecoregion_type[lulc_sep_2020$ecoregion_type == 1|lulc_sep_2020$ecoregion_type == 2] <- "hardwoods" 
lulc_sep_2020$ecoregion_type[lulc_sep_2020$ecoregion_type == 4|lulc_sep_2020$ecoregion_type ==5|lulc_sep_2020$ecoregion_type ==6|lulc_sep_2020$ecoregion_type ==7|lulc_sep_2020$ecoregion_type ==8|lulc_sep_2020$ecoregion_type ==10|lulc_sep_2020$ecoregion_type ==11|lulc_sep_2020$ecoregion_type ==12|lulc_sep_2020$ecoregion_type == 13] <- "conifer" 
lulc_sep_2020$ecoregion_type[lulc_sep_2020$ecoregion_type == 9 | lulc_sep_2020$ecoregion_type == 3] <- "mixed"

#create land use cover code based on 1 = nonforest, 2 = conifer, 3 = hardwood, 4 = mixed, 5 = shrub
 lulc_sep_2020 <- lulc_sep_2020 %>%
   mutate(landcover_code = ecoregion_type)
lulc_sep_2020$landcover_code[lulc_sep_2020$landcover_code == "non-forest" ] <- 1

lulc_sep_2020$landcover_code[lulc_sep_2020$landcover_code == "conifer" ] <- 2

lulc_sep_2020$landcover_code[lulc_sep_2020$landcover_code == "hardwoods" ] <- 3

lulc_sep_2020$landcover_code[lulc_sep_2020$landcover_code == "mixed" ] <- 4

lulc_sep_2020$landcover_code[lulc_sep_2020$landcover_code == "shrub" ] <- 5


#write it out into shape file!
st_write(lulc_sep_2020, "tcsi_landcover_2020.shp")
```
```

